version: "2"
linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - durationcheck
    - errchkjson
    - gocheckcompilerdirectives
    - gochecksumtype
    - gosec
    - gosmopolitan
    - loggercheck
    - makezero
    - misspell
    - musttag
    - nilerr
    - nilnesserr
    - protogetter
    - reassign
    - recvcheck
    - revive
    - rowserrcheck
    - spancheck
    - sqlclosecheck
    - unparam
    - unqueryvet
    - unused
    - usetesting
    - zerologlint
  disable:
    - err113
    - errorlint
    - exhaustive
    - noctx
    - wrapcheck
  settings:
    revive:
      rules:
        - name: unexported-return
          disabled: true
    usetesting:
      context-background: true
      context-todo: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/terramate-io/tmc-stack
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
