version: "2"

run:
  timeout: 5m
  tests: true
  allow-parallel-runners: true

linters:
  default: none
  enable:
    - govet
    - revive
    - errcheck
    - staticcheck
    - ineffassign
    - unused
    - gocyclo
    - goconst
    - nakedret
    - unparam
    - misspell
  settings:
    govet:
      enable:
        - shadow
    gocyclo:
      min-complexity: 15
    goconst:
      min-len: 3
      min-occurrences: 3
    revive:
      rules:
        - name: var-naming
        - name: exported
          arguments: ["checkPrivateReceivers"]
        - name: errorf
        - name: blank-imports
        - name: context-as-argument
        - name: error-return
        - name: increment-decrement
        - name: unexported-return
    misspell:
      locale: US
  exclusions:
    rules:
      - linters: [revive]
        text: "exported: exported function .* should have comment or be unexported"
      - linters: [revive]
        text: "package-comments: should have a package comment"
      - linters: [revive]
        path: "types/"
        text: "var-naming: avoid meaningless package names"
      - linters: [goconst, gocyclo]
        path: "_test\\.go"

formatters:
  enable:
    - gofumpt
  settings:
    gofumpt:
      extra-rules: false

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
