name: 🔨 Build

on:
  push: { branches: [main] }
  pull_request: { branches: [main] }

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    name: 🛠️ Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Check out repository code
        uses: actions/checkout@v5

      - name: Mark source directory as safe
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache: true

      - name: Build binary
        run: make ci-build
        shell: bash

      - name: Verify binary works
        run: ./bin/terramate-mcp-server --help
        shell: bash

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: terramate-mcp-server-${{ matrix.os }}
          path: bin/terramate-mcp-server${{ matrix.os == 'windows-latest' && '.exe' || '' }}
          retention-days: 7
